### ISSUE TITLE
What contains the mapping when in the save callback

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#11]
Basically from this line -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/components/data.mapper.example.host.component.ts#L83

Would `this.cfg.mappings` be the object I'd want to save?

I guess kinda related to https://github.com/redhat-ipaas/datamapper-ui/issues/10 in a way

**Comment by gashcrumb** [comment]
@mattrpav @jbakermd Oops, should have CC'd you guys on this one...

**Comment by mattrpav** [comment]
@gashcrumb see the snippet here: [data.mapper.example.host.component.ts#L106](https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/components/data.mapper.example.host.component.ts#L106)

**Comment by gashcrumb** [comment]
Thanks!
