### ISSUE TITLE
Is a POM needed then?

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#15]
I see in the updated example it sends along a POM file for figuring out the classpath.  I guess this is something we'll generally need then?

@KurtStam wonder, can we include the POM file in the integration somehow?  Maybe as another parameter in `configuredProperties` as a string, like the mapping document.

**Comment by gashcrumb** [comment]
I guess though for the first time through there won't be a POM available at all as there won't be a project yet.

**Comment by gashcrumb** [comment]
Oh, or we can specify a classpath, I see.  Wonder if we could generate that then instead.

**Comment by mattrpav** [comment]
My bad. The maven class path call is the only one wo CORS. 

Re: classpath: I had discussed this approach w @chirino and he thought the CP would not be known bc of pathing issues to DM container's mvn repo. 

I'm open to revisiting the convo; however, we should prolly rally w Chirino to ensure requirements are covered

**Comment by gashcrumb** [comment]
no worries!  But yeah, the classpath/pom thing will be tough, especially if we haven't started any kind of project yet.

Unless I guess we create the project after we get the start/end of the route, then we could have a pom file available.  Definitely will need more discussion :-)

**Comment by chirino** [comment]
Generating a Pom should not be a problem for the rest backend.

**Comment by gashcrumb** [comment]
This should be all set.
