### ISSUE TITLE
Couple dependency things...

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#2]
`ng-bootstrap` only works for bootstrap 4, we're kinda stuck on bootstrap 3.  We're currently using `ng2-bootstrap@1.3.3`  There's syntax differences between the two, so watch out for that -> http://valor-software.com/ng2-bootstrap/#/

Also there's an `angular2` dependency in the package.json file that I think can come out, as all the angular packages are in the @angular namespace.  I think this might be causing some old transitive dependencies to get pulled in.

@mattrpav FYI...

**Comment by gashcrumb** [comment]
Wonder can you also try bumping `rxjs` to 5.1.1?  And would you like a PR for all this?

**Comment by mattrpav** [comment]
PR sounds good.  Curiously, what is the driver for Bootstrap 3?  Something for us to keep an eye on so we don't pull in BS4 accidentally moving forward.

**Comment by gashcrumb** [comment]
Version of patternfly we're on depends on/pulls in bootstrap 3 so we're stuck with it for now.

**Comment by gashcrumb** [comment]
@mattrpav btw, do you know what's being used from ng-bootstrap?

**Comment by gashcrumb** [comment]
never mind, found it :-)

**Comment by mattrpav** [comment]
Type-ahead drop down input box

**Comment by mattrpav** [comment]
We are digging into the ng2-bootstrap@1.3.3 as a replacement

**Comment by gashcrumb** [comment]
k, almost have a PR with an update, here's the docs on it -> http://valor-software.com/ng2-bootstrap/#/typeahead

**Comment by gashcrumb** [comment]
Actually, lemme leave moving to ng2-bootstrap to you, as I can't properly test it here.  Am opening a PR with the other changes though.

**Comment by mattrpav** [comment]
@gashcrumb please review changes and not jasmine-fix.zip work around is no longer needed

**Comment by gashcrumb** [comment]
Think this is all set, thanks!
