### ISSUE TITLE
Missing ajax-loader.gif file

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#20]
Seeing this 404:

GET http://localhost:4200/app/lib/ipaas-data-mapper/ajax-loader.gif 404 (Not Found)

though maybe it'd be better to use the patternfly `spinner` class rather than this gif.

**Comment by jbakermd** [comment]
Issue fixed with commit 3fa8d5b83b54fa6fce49f3bf1ac9533c9a83fd13. Thanks for the pointer about patternfly spinner.
