### ISSUE TITLE
Error when clicking on a field in the UI

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#23]
This actually works with a local dev build, but on the staging instance of the app I get the following when I go to the data mapper page and click on a field.  So close!

<img width="548" alt="capture" src="https://cloud.githubusercontent.com/assets/351660/24675133/0f97ed40-194c-11e7-850f-5e7b3edf7b13.PNG">

**Comment by gashcrumb** [comment]
Seems to correlate to when the side panel with the controls is displayed.

**Comment by gashcrumb** [comment]
Ooh, I think I might know what's causing this actually -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/data.mapper.module.ts#L66 it's probably failing to inject some ng2-bootstrap specific service.  Let me ensure we're initializing the typeahead module in our code and see if that sorts this out.

**Comment by gashcrumb** [comment]
Hmm, the linked PR didn't seem to change the behavior.  I wonder if this component annotation should have `providers` set like:

```
@Component({
   //  ...stuff
  providers: [ DomSanitizer ]
})
```

that's the only other thing I can think of that'd maybe have something to do with this error.

**Comment by gashcrumb** [comment]
Looking at the html in the DOM when the error occurs, I'm wondering if the modal component could be a cause.  One option could be to use the ng2-bootstrap implementation, that'd also mean less code to maintain.  Think the only way to reproduce this that I can see is build the component minified, let me also see if angular 2 has any strict dependency injection checks I could enable that might show more info in dev mode.

**Comment by gashcrumb** [comment]
Can reproduce locally via `yarn ng server -- --prod` so investigating further.

**Comment by gashcrumb** [comment]
Interesting, after using `yarn link` and restarting to pull in the datamapper-ui repo now it doesn't reproduce locally.

**Comment by gashcrumb** [comment]
So did `yarn unlink ipaas.data.mapper`, I can still at least modify the cached copy of the files and reproduce the issue again.  Trying to narrow it down to a particular component, so far I've confirmed that commenting out the mapping-detail component from the data mapper app root template makes the error go away, but haven't narrowed it further yet.

**Comment by gashcrumb** [comment]
@mattrpav any word on this one too?  :-)

**Comment by jbakermd** [comment]
Did adding the ".forRoot()" factory method in the data mapper's module rather than the host module solve the problem for you, @gashcrumb? I confirm on my end that I can run the data mapper standalone with that change.

**Comment by gashcrumb** [comment]
yeah, for me it fixes this issue locally.

**Comment by jbakermd** [comment]
Perfect. I will merge your pull request. Thanks for getting to the bottom of this.
