### ISSUE TITLE
Error loading image from .css file

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#27]
Hit this error pulling in the latest updates:

```
ERROR in ./~/ipaas.data.mapper/src/app/lib/ipaas-data-mapper/components/data.mapper.app.component.css
Module not found: Error: Can't resolve './assets/img/arrow_background.png' in 'C:\Users\gashcrumb\GitHub\ipaas-ui\node_modules\ipaas.data.mapper\src\app\lib\ipaas-data-mapper\components'
 @ ./~/ipaas.data.mapper/src/app/lib/ipaas-data-mapper/components/data.mapper.app.component.css 6:985-1029
 @ ./~/ipaas.data.mapper/src/app/lib/ipaas-data-mapper/components/data.mapper.app.component.ts
 @ ./~/ipaas.data.mapper/src/app/lib/ipaas-data-mapper/data.mapper.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

that's a tough one, as the relative paths are gonna be pretty different when this module is pulled in as a dependency.  If the file isn't too big one option is to base64 encode the image and inline it in the css.

**Comment by gashcrumb** [comment]
Changing the path in the css file to an absolute path seems to fix this for me...

**Comment by gashcrumb** [comment]
I think though I'll have to copy those assets into our project, which I think is fine for now.  Could we align on the path?  We keep our images in `assets/images` vs `assets/img`.

**Comment by jbakermd** [comment]
Right thats what I was thinking the answer would be, a copy job before you build. Can you describe the rest of your assets folder structure for future reference, i.e. is there an "assets/css" or "assets/styles" etc?

**Comment by jbakermd** [comment]
And, what do you think about the following possible folder structures:

"assets/images/dm/" (for data mapper images)

or do you prefer something like:

"assets/dm/images"

or shall we instead just prefix all dm assets with "dm-" such as "dm-bg-image.png" to avoid conflicts?

**Comment by gashcrumb** [comment]
So far just 'images', our css winds up all getting baked into one big file I think, but this is it -> https://github.com/redhat-ipaas/ipaas-ui/tree/master/src/assets

yeah, maybe a 'dm' folder would be best I think, that way if we need to revisit how assets are brought in they're all together.

**Comment by jbakermd** [comment]
perfect. I'll move our assets to a "assets/dm/images" folder in our project, you can then just copy "dm" into "assets/dm" in your project. I'll commit this this evening. Do you need it sooner?

**Comment by gashcrumb** [comment]
Nope, that sounds good to me!

**Comment by gashcrumb** [comment]
@jbakermd @mattrpav oh, went ahead and canceled that call too...

**Comment by mattrpav** [comment]
Good deal =)

**Comment by jimmidyson** [comment]
Any news on this fix?

**Comment by jbakermd** [comment]
I've changed the layout of the files in the latest commit. 

@gashcrumb as we discussed the images in the DM project have been moved from a "assets/img" layout to "assets/dm/images", with the intention of your build job copying the "dm" folder into your "assets" folder before compilation. 

I'll leave this issue open until you've been able to update your build job with this new file structure.

**Comment by gashcrumb** [comment]
Great, thanks!  I'll give it a try right now...

**Comment by gashcrumb** [comment]
@jbakermd I still get the compilation error, but I see that this line is still a relative path -> https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/components/data.mapper.app.component.css#L20 in the latest commit, this needs to be an absolute path.

Kinda seems like a webpack bug but that being said it's trying to load it relative to the .css file, so it's an accurate enough error, as that file path is certainly relative to `index.html` but not to the location of the `data.mapper.app.component.css` file.  So quick fix, lets make this an absolute path.

**Comment by jbakermd** [comment]
Ok the latest commit (https://github.com/redhat-ipaas/datamapper-ui/commit/c6ac2fb32283893a43c3c1e33ead461ebd223734) should fix this. Let me know if it doesn't.
