### ISSUE TITLE
DataMapperUIBackground div at 200% height

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#29]
Makes the whole page taller than it should be.  We're currently optimizing for 1280x720 for the demo, I think it's probably best to `avoid height: 200%` rule.  Note that the container that I'm loading the data mapper component in is set up like:

```
    .data-mapper-host {
        /* TODO probably a better way to set this height to the viewport */
        height: calc(100vh - 140px);
      }
```

So 100% of the viewport less the (apparently) 140 pixels for the header.

![screencapture-localhost-4200-integrations-edit-1-step-configure-2-1491500016281](https://cloud.githubusercontent.com/assets/351660/24767640/a73f1c36-1acd-11e7-8aaf-dfd750efaacb.png)

**Comment by jbakermd** [comment]
Right. This was a temporary hack I forgot to fix yesterday afternoon as I was working on that background. The height needs to be 100%, and some work in the data mapper's main div needs to be done to make that 100% show up correctly. 

I might resort to the main div saying overflow:none, in which case the 200% inner element here won't affect anything.

**Comment by gashcrumb** [comment]
Sounds good.  There seems to also be some padding/margins that make the data mapper elements kind of 'spill out' of the container div we have, so I wind up having to make our container smaller than I think it could be.  Maybe it's worth in the components development index.html perhaps setting the same CSS on the container?  Or actually I guess it'd be in the example component.  In any case, might help with alignment...

**Comment by jbakermd** [comment]
I've fixed the "spilling out" issue (bad math regarding height of the mapper's child components), and the 200% background height. That checkin will be happening soon.

Can you provide the index.html you're using so I can align our test index as closely to it as possible?

**Comment by gashcrumb** [comment]
Awesome!

Kind of tough as there's a few layers of components -> https://github.com/redhat-ipaas/ipaas-ui/blob/master/src/index.html

The actual component that's currently holding the datamapper is (markup/css is inline in this file) -> https://github.com/redhat-ipaas/ipaas-ui/blob/master/src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts

**Comment by jbakermd** [comment]
Right. We could "copy outer html" in the chrome inspection tool from the top of the "current html" shown there, but that's going to be a world of hurt as well. I'm fairly certain I've fixed the spill over issue, which should make the data mapper ui play nice within whatever container it's placed in. Let's see if that works out for you in your container, and if not we can come back to trying to align pixel for pixel again.

**Comment by gashcrumb** [comment]
Yep, that sounds good.

**Comment by jbakermd** [comment]
@gashcrumb  this is fixed in the latest commit.
