### ISSUE TITLE
Inherit font/font-size for consistency with enclosing app

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#32]
Looks like the css specifies OpenSans for font-family and a font-size it'd be better to let that get inherited from the containing app.  For font-size use relative sizes perhaps?

**Comment by jbakermd** [comment]
Related Comments from #36

- Fonts are inconsistent with what's used elsewhere in the iPaaS UI. (from @kcbabo)

**Comment by jbakermd** [comment]
First fix this is in 1f480d28be5789aad1da93b5714f66ed88be47e5.

For starters I simply removed the datamapper-wide font face and size override, though various elements (quite a few, actually) still have font-size overrides within them. I think overall the data mapper looks better with just these simple fixes.

@gashcrumb @kcbabo, check out the data mapper ui font L&F with these fixes, and LMK if you think we should further refine font sizes / boldness / faces for any data mapper elements.

**Comment by jbakermd** [comment]
Marking this issue as closed. Feel free to reopen if needed for further font property refinement.
