### ISSUE TITLE
modal styling

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#38]
I think I caught a look at the modal styling and it doesn't really follow the patternfly look like I would have expected.  This makes it really stick out consistency-wise.

**Comment by gashcrumb** [comment]
Was going to suggest also might be worth using ng2-bootstrap's modal directive, it plays nicely with the patternfly styling, for example -> https://github.com/redhat-ipaas/ipaas-ui/blob/master/src/app/integrations/list/list.component.html#L8-L33

**Comment by jbakermd** [comment]
Hey @gashcrumb, can you point me to an example use case within the iPAAS UI to see the iPAAS modal in action for styling consistency investigation?

**Comment by gashcrumb** [comment]
Hey!  Yeah go to the integration list and pick delete or
activate/deactivate, those all use modals.  Thanks!

**Comment by jbakermd** [comment]
Fixed with 680773bf314ceda5b1bd5252144827d1b8d2060c.
