### ISSUE TITLE
Background is inconsistent with overall iPAAS UI.

### ISSUE THREAD

**Issue by jbakermd** [redhat-ipaas/datamapper-ui#42]
This issue was first mentioned in the general L&F Issue (#36)

Comments for this issue from #36:

- Background image is distracting - need to have a neutral/blended background. (from @gashcrumb)

- I don't recall the designs having that dark background image, @kcbabo? I kinda feel like it'd be better if the component just inherits the container's background instead. (from @kcbabo)

**Comment by jbakermd** [comment]
Ok I committed 1f480d28be5789aad1da93b5714f66ed88be47e5 with a *partial* fix to this. At first I removed not only the background arrow image, but also the dark grey color for the background, but that didn't look very good imo: 

![screen shot 2017-04-12 at 4 06 16 pm](https://cloud.githubusercontent.com/assets/26657480/24980347/73e037c4-1f9d-11e7-8b27-03e2e96d7c83.png)

So, I put the dark grey background (without the arrows image) back in for now:

![screen shot 2017-04-12 at 4 06 48 pm](https://cloud.githubusercontent.com/assets/26657480/24980366/7eefee2a-1f9d-11e7-9313-a6e606497aa9.png)

@gashcrumb  @kcbabo, any opinions on this? Yank the dark background out and go to the light grey shown in the top image, or?

**Comment by kcbabo** [comment]
I find the dark gray background a bit distracting.  Part of the problem is that the UI elements don't appear to be spaced evenly on the background and the source model is off the side. 

Would be curious to hear what @sjcox-rh and @dongniwang think.

**Comment by jbakermd** [comment]
I have removed the dark gray background (commit b2619d9a7f9fd9d52227fb31e4fea41d3512d7aa). Lmk if it should be added back in.

**Comment by jbakermd** [comment]
Marking this issue as closed. Feel free to reopen it if the dark grey background should be reintroduced.
