### ISSUE TITLE
Data mapper alignment problems within iPAAS UI

### ISSUE THREAD

**Issue by jbakermd** [redhat-ipaas/datamapper-ui#44]
This issue was first mentioned in the general L&F Issue (#36)

Comments from #36:

Open Issues: 

- Text used in source and model view headers (model names) do not align with text boxes. (from @kcbabo) 

Fixed Issues:

- Model viewer frames are not aligned to the overall UI - the source model hangs off the left side and the mapping actions frame is off to the right. (from @kcbabo) (fixed with b2619d9a7f9fd9d52227fb31e4fea41d3512d7aa)

- Model viewers get kind of funky when resizing the browser window.  (from @kcbabo) (fixed with b2619d9a7f9fd9d52227fb31e4fea41d3512d7aa)

**Comment by jbakermd** [comment]
@kcbabo I need some clarification on "Text used in source and model view headers (model names) do not align with text boxes." 

Here is a screenshot to facilitate this discussion:

![screen shot 2017-04-12 at 4 54 05 pm](https://cloud.githubusercontent.com/assets/26657480/24981196/3132bef2-1fa1-11e7-9bba-304254312205.png)

Are the green lines above indicating what you're talking about? The green lines show that the "Status" header and it's icon do not align with the left edge of the field icons.

And/or is the yellow line what you're talking about? That line indicates that the hard drive icon for Status is vertically aligned to the bottom of the word "Status", should we move this to a middle alignment?

**Comment by kcbabo** [comment]
Let me grab the latest build and screen capture what I'm seeing.

**Comment by jbakermd** [comment]
Sounds good. Btw the fix isn't in yet, but I have the fix for the model cards overlapping outside the bounding box, and the resize issue.

**Comment by kcbabo** [comment]
OK, it's tough for me to provide any feedback without seeing it in context.  Do you know when the changes for background, fonts, and alignment will be pushed?

**Comment by kcbabo** [comment]
Updated comments using the latest build:
- I now see visual indicators for fields that have been mapped
- Model views come up lightning fast
- The mapping edge is drawn super fast when I map fields
- Alignment of model names does not get funky when I resize the window.  I think this one might be a bit of a cheat though because we moved to just showing the simple class name vs. the fully-qualified class name.  I think there's an issue when resizing the UI to where it truncates part of the model name.

Great progress on all the above points!  Looking forward to seeing the font and background updates.

**Comment by jbakermd** [comment]
@kcbabo If you don't mind, can you pull latest one more time and review for further comment? I just fixed a number of alignment issues with b2619d9a7f9fd9d52227fb31e4fea41d3512d7aa. 

Namely one important one I fixed is the issue with a toolbar showing up while loading, when it should have been hidden until loading completed.

Others are noted in the description for the issue at the top of this thread (cards spilling outside of containing box, cards not resizing well).

**Comment by jbakermd** [comment]
@kcbabo Can you elaborate on the following points:

Question 1: Alignment of model names. Are you talking about the green line or the yellow line shown in this image?

![screen shot 2017-04-12 at 4 54 05 pm](https://cloud.githubusercontent.com/assets/26657480/24983924/e31e9cf4-1faf-11e7-9a3c-796fff48c309.png)

Question 2: Can you provide a screenshot showing the model name being truncated? I've tried resizing the browser window very small and the entire UI disappears before I see any truncation of the model name.

**Comment by jbakermd** [comment]
Yellow line issue and long model name issues are fixed with ced74f8d9d1bdd0d2f9c3600c75167344e4843cd. 

@kcbabo when you get a chance, update and lmk of any further alignment issues you see.

**Comment by jbakermd** [comment]
I've fixed a few more alignment issues I've noticed. (commit 680773bf314ceda5b1bd5252144827d1b8d2060c) Feel free to reopen if necessary.

**Comment by kcbabo** [comment]
Data mapper is looking super sweet after your last round of changes.  Nice work!
