### ISSUE TITLE
Model name too big for text area

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/datamapper-ui#58]
Check out the g's in Suggestion - they get clipped at the bottom.  Maybe add more buffer or drop the font size a bit?

![image](https://cloud.githubusercontent.com/assets/340837/25243649/ca81ea58-25cb-11e7-9e48-3bdd846b4c57.png)

**Comment by kcbabo** [comment]
@chirino @mattrpav FYI

**Comment by jbakermd** [comment]
It's the size of the box around the font (buffer) that's the problem. Will fix.

**Comment by jbakermd** [comment]
Fixed with 64c6de0a56465cd495cf64dc24d698ffcae54f9e.
