### ISSUE TITLE
target/source field header text is cut off at the bottom

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#63]
@mattrpav on Keith's demo I noticed the 'gg' in 'Suggestion' was cut off at the bottom, either the element needs a little more padding or maybe it's set 'overflow: hidden' and maybe doesn't need to be.

**Comment by gashcrumb** [comment]
@kcbabo @chirino wonder, can we get those connections/integrations added to the example deployment.yaml so the mediadriver folks can see it too?

**Comment by jbakermd** [comment]
I fixed this yesterday per #58 at 4:30 central. I *think* the demo was run without latest code, but I'm double checking.

**Comment by jbakermd** [comment]
Yeah, I confirm this is fixed. Dupe of #58. Pull latest from Data Mapper UI git and lmk if you see the issue still.

**Comment by gashcrumb** [comment]
Ah, okay sorry I didn't see that, thanks!

**Comment by jbakermd** [comment]
@gashcrumb no worries.
